version: '3.8'
services:
  web:
    image: nginx:alpine
    volumes:
      - /opt/undercover/dist:/usr/share/nginx/html:ro
      - /opt/undercover/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
      - "443:443"

  peerjs:
    image: peerjs/peerjs-server
    environment:
      - KEY=peerjs
    # → entferne hier den "9000:9000", wenn Du PeerJS nur via Nginx-Proxy erreichen willst
