version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      # - "443:443"  ← falls du HTTPS später einrichtest

  peerjs:
    image: peerjs/peerjs-server
    command: peerjs --port 9000 --path /peerjs
    # expose statt ports, weil wir ausschließlich über Nginx proxyen
    expose:
      - "9000"
